//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace votingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option
    {
        public int OptionId { get; set; }
        public int PollId { get; set; }
        public int CandidateId { get; set; }
        public int Count { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual Poll Poll { get; set; }
    }
}
