//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace voting.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int UserId { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [MinLength(1)]
        [MaxLength(50)]
        [RegularExpression("^[a-zA-Z]+$", ErrorMessage = "Please use letters only")]
        public string Name { get; set; }



        [DisplayName("Aadhar Number")]
        [Required(ErrorMessage = "This field is required")]
        [MinLength(12)]
        [MaxLength(12)]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Adhar Number must be Numeric")]
        public string AadharNumber { get; set; }




        public byte UserType { get; set; }


        [DisplayName("Username")]
        [Required(ErrorMessage = "This field is required")]
        public string UserName { get; set; }



        [Required(ErrorMessage = "This field is required")]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[$@$!%*?&])[A-Za-z\d$@$!%*?&]{6,}$", ErrorMessage = "Password must contain: Minimum 8 characters atleast 1 UpperCase Alphabet, 1 LowerCase Alphabet, 1 Number and 1 Special Character")]
        [DataType(DataType.Password)]
        public string Password { get; set; }


        [DisplayName("Confirm Password")]
        [Required(ErrorMessage = "This field is required")]
        [DataType(DataType.Password)]
        [Compare("Password")]
        public string ConfirmPassword { get; set; }
    }
}
